---
title: "Homework_12"
author: "Al Freeman"
date: '2022-04-20'
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(viridis) #Scale-fill for ggplot
library(ggplot2)
library(gridExtra)


licor <- read.csv("survey_data_all.csv")

survey <- select(licor, Date, ID, species, treatment, Photo, Cond, intr_WUE)
head(survey)
```

```{r}
#### Establish Black Theme #### I use this customized black theme for presentations since my slides are black
theme_black = function(base_size = 12, base_family = "") {
  
  theme_grey(base_size = base_size, base_family = base_family) %+replace%
    
    theme(
      # Specify axis options
      axis.line = element_blank(),  
      axis.text.x = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.text.y = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.ticks = element_line(color = "white", size  =  0.2),  
      axis.title.x = element_text(size = base_size, color = "white", margin = margin(0, 10, 0, 0)),  
      axis.title.y = element_text(size = base_size, color = "white", angle = 90, margin = margin(0, 10, 0, 0)),  
      axis.ticks.length = unit(0.3, "lines"),   
      # Specify legend options
      legend.background = element_rect(color = NA, fill = "black"),  
      legend.key = element_rect(color = "white",  fill = "black"),  
      legend.key.size = unit(1.2, "lines"),  
      legend.key.height = NULL,  
      legend.key.width = NULL,      
      legend.text = element_text(size = base_size*0.8, color = "white"),  
      legend.title = element_text(size = base_size*0.8, face = "bold", hjust = 0, color = "white"),  
      legend.position = "right",  
      legend.text.align = NULL,  
      legend.title.align = NULL,  
      legend.direction = "vertical",  
      legend.box = NULL, 
      # Specify panel options
      panel.background = element_rect(fill = "black", color  =  NA),  
      panel.border = element_rect(fill = NA, color = "white"),  
      panel.grid.major = element_line(color = "black"),  #can change color for gridlines
      panel.grid.minor = element_line(color = "black"),  
      panel.margin = unit(0.5, "lines"),   
      # Specify facetting options
      strip.background = element_rect(fill = "grey30", color = "grey10"),  
      strip.text.x = element_text(size = base_size*0.8, color = "white"),  
      strip.text.y = element_text(size = base_size*0.8, color = "white",angle = -90),  
      # Specify plot options
      plot.background = element_rect(color = "black", fill = "black"),  
      plot.title = element_text(size = base_size*1.2, color = "white"),  
      plot.margin = unit(rep(1, 4), "lines")
      
    )
  
}

```

```{r}

#### All species photosynthesis 
ggplot(survey, aes(x=Date, y=Photo, fill = species, color = species)) + geom_boxplot() +
  scale_fill_manual(values=c("darkslategray", "antiquewhite4","goldenrod")) +
  scale_color_manual(values = c("white", "white", "white"))+
  ylab(bquote('A ('*mu~ 'mol' ~CO[2]~ m^-2~s^-1*')')) +
  facet_wrap(~species) +
  scale_y_continuous(name = "Photosynthetic Capacity") +
  theme_black() +
  theme(strip.background = element_blank(), strip.text.x = element_text(size = 20, color = "white", face = "bold"), 
        axis.text.x=element_text(angle = 60, vjust = 0.5, size = 15), 
        axis.text.y=element_text(size = 15),
        axis.title.y.left = element_text(size = 20, vjust = 2),
        axis.title.y.right = element_text(size = 20, vjust = 4),
        axis.title.x = element_blank()) 


#### All species photosynthesis 
ggplot(survey, aes(x=Date, y=Photo, fill = species, color = species)) + geom_boxplot() +
  scale_fill_manual(values=c("darkslategray", "antiquewhite4","goldenrod")) +
  ylab(bquote('A ('*mu~ 'mol' ~CO[2]~ m^-2~s^-1*')')) +
  facet_wrap(~species) +
  scale_y_continuous(name = "Photosynthetic Capacity") +
  theme_dark() +
  theme(strip.background = element_blank(), strip.text.x = element_text(size = 20, color = "black", face = "bold"), 
        axis.text.x=element_text(angle = 60, vjust = 0.5, size = 15), 
        axis.text.y=element_text(size = 15),
        axis.title.y.left = element_text(size = 20, vjust = 2),
        axis.title.y.right = element_text(size = 20, vjust = 4),
        axis.title.x = element_blank())

```



